In [2]:
import numpy as np
import scipy.ndimage as nd
import matplotlib.pyplot as plt


In [3]:
#Limits for Floating point
eps = np.finfo(float).eps

In [44]:
#Load image
img = plt.imread('rice.png')
mask = np.zeros(img.shape)
print(img.shape)
mask[20:100, 20:100] = 1
img = img.astype(np.float) #convert to np.float

(256, 256)


In [11]:
# Create a signed distance from mask
def bwdist(a):
    """
    Exact Euclidean distance transform.
    Input: a is an array 
    """
    return nd.distance_transform_edt(a == 0)
a = np.array(([0,1,1,1,1],
              [0,0,1,1,1],
              [0,1,1,1,1],
              [0,1,1,1,0],
              [0,1,1,0,0]))
#print(bwdist(a))
def im2double(a):
    '''
    Input: a is an array
    Output: return an array that has elements in [0,1]
    '''
    a = a.astype(np.float)
    a /= np.abs(a).max()
    return a
def mask2phi(init_a):
    phi = bwdist(init_a) - bwdist(1 - init_a) + im2double(init_a) - 0.5
    return phi
print(mask2phi(a))

[[ 0.5        -0.5        -0.91421356 -1.73606798 -2.5       ]
 [ 0.91421356  0.5        -0.5        -1.5        -1.5       ]
 [ 0.5        -0.5        -0.91421356 -0.91421356 -0.5       ]
 [ 0.5        -0.5        -0.91421356 -0.5         0.5       ]
 [ 0.5        -0.5        -0.5         0.5         0.91421356]]


In [31]:
phi = mask2phi(mask)
#Gets indices of Phi's elements in [-1.2; 1.2]
idx = np.flatnonzero(np.logical_and(phi <= 1.2, phi >= -1.2))
print(idx.shape)
print(phi.shape)

(1920,)
(132, 132, 3)


In [43]:
    dimy, dimx, _ = phi.shape
    yx = np.array([np.unravel_index(i, phi.shape) for i in idx])  # subscripts
    y = yx[:, 0]
    x = yx[:, 1]
    print(dimy)

132


In [42]:
img_channel0 = img[:,:,0]
img_channel1 = img[:,:,1]
img_channel2 = img[:,:,2]
import matplotlib
img_channel1 = img[:,:,1]
img_channel1

array([[0.11764706, 0.10980392, 0.09803922, ..., 0.19215687, 0.2       ,
        0.19215687],
       [0.12156863, 0.11372549, 0.10588235, ..., 0.19215687, 0.1882353 ,
        0.16862746],
       [0.12941177, 0.12156863, 0.11372549, ..., 0.20392157, 0.2       ,
        0.19215687],
       ...,
       [0.17647059, 0.16470589, 0.14901961, ..., 0.03529412, 0.03137255,
        0.02352941],
       [0.16470589, 0.15686275, 0.14901961, ..., 0.04313726, 0.03137255,
        0.01960784],
       [0.15686275, 0.15294118, 0.14509805, ..., 0.0627451 , 0.04313726,
        0.02745098]])

In [41]:
img_channel2

array([[0.11764706, 0.10980392, 0.09803922, ..., 0.19215687, 0.2       ,
        0.19215687],
       [0.12156863, 0.11372549, 0.10588235, ..., 0.19215687, 0.1882353 ,
        0.16862746],
       [0.12941177, 0.12156863, 0.11372549, ..., 0.20392157, 0.2       ,
        0.19215687],
       ...,
       [0.17647059, 0.16470589, 0.14901961, ..., 0.03529412, 0.03137255,
        0.02352941],
       [0.16470589, 0.15686275, 0.14901961, ..., 0.04313726, 0.03137255,
        0.01960784],
       [0.15686275, 0.15294118, 0.14509805, ..., 0.0627451 , 0.04313726,
        0.02745098]])